name: Build APK + Deploy Web

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.29.2

      - run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Build Web
        run: flutter build web --release

      - uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Deploy to HF Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.name "Haris-Ahmed83"
          git config --global user.email "haris@example.com"
          git clone https://Haris-83:$HF_TOKEN@huggingface.co/spaces/Haris-83/chato hf-space
          cd hf-space
          rm -rf *
          cp -r ../build/web/* .
          rm -rf canvaskit
          echo '---' > README.md
          echo 'title: Chato' >> README.md
          echo -e 'emoji: \U0001F4AC' >> README.md
          echo 'colorFrom: green' >> README.md
          echo 'colorTo: blue' >> README.md
          echo 'sdk: static' >> README.md
          echo 'pinned: false' >> README.md
          echo '---' >> README.md
          git add -A
          git diff --cached --quiet || {
            git commit -m "auto-deploy from GitHub Actions"
            git push
          }
